/********************************************************************************
** Form generated from reading UI file 'placeswindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PLACESWINDOW_H
#define UI_PLACESWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_PlacesWindow
{
public:
    QPushButton *place_72;
    QPushButton *place_80;
    QPushButton *place_56;
    QPushButton *place_85;
    QPushButton *place_61;
    QPushButton *place_101;
    QPushButton *place_69;
    QPushButton *place_109;
    QPushButton *place_14;
    QPushButton *place_22;
    QPushButton *place_114;
    QPushButton *place_27;
    QPushButton *place_75;
    QPushButton *place_83;
    QPushButton *place_45;
    QPushButton *place_17;
    QPushButton *place_50;
    QPushButton *place_25;
    QPushButton *place_58;
    QPushButton *place_119;
    QPushButton *place_46;
    QPushButton *place_65;
    QPushButton *place_95;
    QPushButton *place_33;
    QPushButton *place_79;
    QPushButton *place_87;
    QPushButton *place_63;
    QPushButton *place_103;
    QPushButton *place_92;
    QPushButton *place_68;
    QPushButton *place_108;
    QPushButton *place_116;
    QPushButton *place_31;
    QPushButton *place_21;
    QPushButton *place_121;
    QPushButton *place_77;
    QPushButton *place_98;
    QPushButton *place_104;
    QPushButton *place_82;
    QPushButton *place_90;
    QPushButton *place_106;
    QPushButton *place_19;
    QPushButton *place_38;
    QPushButton *place_52;
    QPushButton *place_24;
    QPushButton *place_48;
    QPushButton *place_36;
    QPushButton *place_53;
    QPushButton *place_12;
    QPushButton *place_4;
    QPushButton *place_81;
    QPushButton *place_7;
    QPushButton *place_86;
    QPushButton *place_94;
    QPushButton *place_70;
    QPushButton *place_110;
    QPushButton *place_8;
    QPushButton *place_115;
    QPushButton *place_30;
    QPushButton *place_40;
    QPushButton *place_84;
    QPushButton *place_9;
    QPushButton *place_111;
    QPushButton *place_57;
    QPushButton *place_113;
    QPushButton *place_26;
    QPushButton *place_59;
    QPushButton *place_71;
    QPushButton *place_47;
    QPushButton *place_55;
    QPushButton *place_29;
    QPushButton *place_37;
    QPushButton *place_60;
    QPushButton *place_100;
    QPushButton *place_34;
    QPushButton *place_13;
    QPushButton *place_96;
    QPushButton *place_15;
    QPushButton *place_88;
    QPushButton *place_74;
    QPushButton *place_35;
    QPushButton *place_93;
    QPushButton *place_97;
    QPushButton *place_117;
    QPushButton *place_32;
    QPushButton *place_44;
    QPushButton *place_122;
    QPushButton *place_16;
    QPushButton *place_89;
    QPushButton *place_99;
    QPushButton *place_6;
    QPushButton *place_91;
    QPushButton *place_118;
    QPushButton *place_64;
    QPushButton *place_1;
    QPushButton *place_66;
    QPushButton *place_28;
    QPushButton *place_73;
    QPushButton *place_49;
    QPushButton *place_78;
    QPushButton *place_39;
    QPushButton *place_54;
    QPushButton *place_3;
    QPushButton *place_62;
    QPushButton *place_102;
    QPushButton *place_67;
    QPushButton *place_107;
    QPushButton *place_20;
    QPushButton *place_76;
    QPushButton *place_42;
    QPushButton *place_105;
    QPushButton *place_41;
    QPushButton *place_43;
    QPushButton *place_18;
    QPushButton *place_51;
    QPushButton *place_23;
    QPushButton *place_112;
    QPushButton *place_11;
    QPushButton *place_120;
    QPushButton *place_5;
    QPushButton *place_10;
    QPushButton *place_2;
    QPushButton *choosePlacesButton;
    QPushButton *backButton;

    void setupUi(QDialog *PlacesWindow)
    {
        if (PlacesWindow->objectName().isEmpty())
            PlacesWindow->setObjectName(QString::fromUtf8("PlacesWindow"));
        PlacesWindow->resize(1066, 600);
        PlacesWindow->setMinimumSize(QSize(1066, 600));
        PlacesWindow->setMaximumSize(QSize(1066, 600));
        PlacesWindow->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 199, 27);"));
        place_72 = new QPushButton(PlacesWindow);
        place_72->setObjectName(QString::fromUtf8("place_72"));
        place_72->setGeometry(QRect(650, 280, 30, 30));
        place_72->setMinimumSize(QSize(30, 30));
        place_72->setMaximumSize(QSize(30, 30));
        place_72->setContextMenuPolicy(Qt::NoContextMenu);
        place_72->setIconSize(QSize(30, 30));
        place_72->setAutoDefault(false);
        place_80 = new QPushButton(PlacesWindow);
        place_80->setObjectName(QString::fromUtf8("place_80"));
        place_80->setGeometry(QRect(450, 320, 30, 30));
        place_80->setMinimumSize(QSize(30, 30));
        place_80->setMaximumSize(QSize(30, 30));
        place_80->setContextMenuPolicy(Qt::NoContextMenu);
        place_80->setIconSize(QSize(30, 30));
        place_80->setAutoDefault(false);
        place_56 = new QPushButton(PlacesWindow);
        place_56->setObjectName(QString::fromUtf8("place_56"));
        place_56->setGeometry(QRect(530, 240, 30, 30));
        place_56->setMinimumSize(QSize(30, 30));
        place_56->setMaximumSize(QSize(30, 30));
        place_56->setContextMenuPolicy(Qt::NoContextMenu);
        place_56->setIconSize(QSize(30, 30));
        place_56->setAutoDefault(false);
        place_85 = new QPushButton(PlacesWindow);
        place_85->setObjectName(QString::fromUtf8("place_85"));
        place_85->setGeometry(QRect(650, 320, 30, 30));
        place_85->setMinimumSize(QSize(30, 30));
        place_85->setMaximumSize(QSize(30, 30));
        place_85->setContextMenuPolicy(Qt::NoContextMenu);
        place_85->setIconSize(QSize(30, 30));
        place_85->setAutoDefault(false);
        place_61 = new QPushButton(PlacesWindow);
        place_61->setObjectName(QString::fromUtf8("place_61"));
        place_61->setGeometry(QRect(730, 240, 30, 30));
        place_61->setMinimumSize(QSize(30, 30));
        place_61->setMaximumSize(QSize(30, 30));
        place_61->setContextMenuPolicy(Qt::NoContextMenu);
        place_61->setIconSize(QSize(30, 30));
        place_61->setAutoDefault(false);
        place_101 = new QPushButton(PlacesWindow);
        place_101->setObjectName(QString::fromUtf8("place_101"));
        place_101->setGeometry(QRect(770, 360, 30, 30));
        place_101->setMinimumSize(QSize(30, 30));
        place_101->setMaximumSize(QSize(30, 30));
        place_101->setContextMenuPolicy(Qt::NoContextMenu);
        place_101->setIconSize(QSize(30, 30));
        place_101->setAutoDefault(false);
        place_69 = new QPushButton(PlacesWindow);
        place_69->setObjectName(QString::fromUtf8("place_69"));
        place_69->setGeometry(QRect(530, 280, 30, 30));
        place_69->setMinimumSize(QSize(30, 30));
        place_69->setMaximumSize(QSize(30, 30));
        place_69->setContextMenuPolicy(Qt::NoContextMenu);
        place_69->setIconSize(QSize(30, 30));
        place_69->setAutoDefault(false);
        place_109 = new QPushButton(PlacesWindow);
        place_109->setObjectName(QString::fromUtf8("place_109"));
        place_109->setGeometry(QRect(570, 400, 30, 30));
        place_109->setMinimumSize(QSize(30, 30));
        place_109->setMaximumSize(QSize(30, 30));
        place_109->setContextMenuPolicy(Qt::NoContextMenu);
        place_109->setIconSize(QSize(30, 30));
        place_109->setAutoDefault(false);
        place_14 = new QPushButton(PlacesWindow);
        place_14->setObjectName(QString::fromUtf8("place_14"));
        place_14->setGeometry(QRect(410, 120, 30, 30));
        place_14->setMinimumSize(QSize(30, 30));
        place_14->setMaximumSize(QSize(30, 30));
        place_14->setContextMenuPolicy(Qt::NoContextMenu);
        place_14->setIconSize(QSize(30, 30));
        place_14->setAutoDefault(false);
        place_22 = new QPushButton(PlacesWindow);
        place_22->setObjectName(QString::fromUtf8("place_22"));
        place_22->setGeometry(QRect(730, 120, 30, 30));
        place_22->setMinimumSize(QSize(30, 30));
        place_22->setMaximumSize(QSize(30, 30));
        place_22->setContextMenuPolicy(Qt::NoContextMenu);
        place_22->setIconSize(QSize(30, 30));
        place_22->setAutoDefault(false);
        place_114 = new QPushButton(PlacesWindow);
        place_114->setObjectName(QString::fromUtf8("place_114"));
        place_114->setGeometry(QRect(770, 400, 30, 30));
        place_114->setMinimumSize(QSize(30, 30));
        place_114->setMaximumSize(QSize(30, 30));
        place_114->setContextMenuPolicy(Qt::NoContextMenu);
        place_114->setIconSize(QSize(30, 30));
        place_114->setAutoDefault(false);
        place_27 = new QPushButton(PlacesWindow);
        place_27->setObjectName(QString::fromUtf8("place_27"));
        place_27->setGeometry(QRect(410, 160, 30, 30));
        place_27->setMinimumSize(QSize(30, 30));
        place_27->setMaximumSize(QSize(30, 30));
        place_27->setContextMenuPolicy(Qt::NoContextMenu);
        place_27->setIconSize(QSize(30, 30));
        place_27->setAutoDefault(false);
        place_75 = new QPushButton(PlacesWindow);
        place_75->setObjectName(QString::fromUtf8("place_75"));
        place_75->setGeometry(QRect(770, 280, 30, 30));
        place_75->setMinimumSize(QSize(30, 30));
        place_75->setMaximumSize(QSize(30, 30));
        place_75->setContextMenuPolicy(Qt::NoContextMenu);
        place_75->setIconSize(QSize(30, 30));
        place_75->setAutoDefault(false);
        place_83 = new QPushButton(PlacesWindow);
        place_83->setObjectName(QString::fromUtf8("place_83"));
        place_83->setGeometry(QRect(570, 320, 30, 30));
        place_83->setMinimumSize(QSize(30, 30));
        place_83->setMaximumSize(QSize(30, 30));
        place_83->setContextMenuPolicy(Qt::NoContextMenu);
        place_83->setIconSize(QSize(30, 30));
        place_83->setAutoDefault(false);
        place_45 = new QPushButton(PlacesWindow);
        place_45->setObjectName(QString::fromUtf8("place_45"));
        place_45->setGeometry(QRect(610, 200, 30, 30));
        place_45->setMinimumSize(QSize(30, 30));
        place_45->setMaximumSize(QSize(30, 30));
        place_45->setContextMenuPolicy(Qt::NoContextMenu);
        place_45->setIconSize(QSize(30, 30));
        place_45->setAutoDefault(false);
        place_17 = new QPushButton(PlacesWindow);
        place_17->setObjectName(QString::fromUtf8("place_17"));
        place_17->setGeometry(QRect(530, 120, 30, 30));
        place_17->setMinimumSize(QSize(30, 30));
        place_17->setMaximumSize(QSize(30, 30));
        place_17->setContextMenuPolicy(Qt::NoContextMenu);
        place_17->setIconSize(QSize(30, 30));
        place_17->setAutoDefault(false);
        place_50 = new QPushButton(PlacesWindow);
        place_50->setObjectName(QString::fromUtf8("place_50"));
        place_50->setGeometry(QRect(810, 200, 30, 30));
        place_50->setMinimumSize(QSize(30, 30));
        place_50->setMaximumSize(QSize(30, 30));
        place_50->setContextMenuPolicy(Qt::NoContextMenu);
        place_50->setIconSize(QSize(30, 30));
        place_50->setAutoDefault(false);
        place_25 = new QPushButton(PlacesWindow);
        place_25->setObjectName(QString::fromUtf8("place_25"));
        place_25->setGeometry(QRect(850, 120, 30, 30));
        place_25->setMinimumSize(QSize(30, 30));
        place_25->setMaximumSize(QSize(30, 30));
        place_25->setContextMenuPolicy(Qt::NoContextMenu);
        place_25->setIconSize(QSize(30, 30));
        place_25->setAutoDefault(false);
        place_58 = new QPushButton(PlacesWindow);
        place_58->setObjectName(QString::fromUtf8("place_58"));
        place_58->setGeometry(QRect(610, 240, 30, 30));
        place_58->setMinimumSize(QSize(30, 30));
        place_58->setMaximumSize(QSize(30, 30));
        place_58->setContextMenuPolicy(Qt::NoContextMenu);
        place_58->setIconSize(QSize(30, 30));
        place_58->setAutoDefault(false);
        place_119 = new QPushButton(PlacesWindow);
        place_119->setObjectName(QString::fromUtf8("place_119"));
        place_119->setGeometry(QRect(514, 440, 94, 51));
        place_119->setMinimumSize(QSize(94, 51));
        place_119->setMaximumSize(QSize(94, 51));
        place_119->setContextMenuPolicy(Qt::NoContextMenu);
        place_119->setIconSize(QSize(94, 51));
        place_119->setAutoDefault(false);
        place_46 = new QPushButton(PlacesWindow);
        place_46->setObjectName(QString::fromUtf8("place_46"));
        place_46->setGeometry(QRect(650, 200, 30, 30));
        place_46->setMinimumSize(QSize(30, 30));
        place_46->setMaximumSize(QSize(30, 30));
        place_46->setContextMenuPolicy(Qt::NoContextMenu);
        place_46->setIconSize(QSize(30, 30));
        place_46->setAutoDefault(false);
        place_65 = new QPushButton(PlacesWindow);
        place_65->setObjectName(QString::fromUtf8("place_65"));
        place_65->setGeometry(QRect(890, 240, 30, 30));
        place_65->setMinimumSize(QSize(30, 30));
        place_65->setMaximumSize(QSize(30, 30));
        place_65->setContextMenuPolicy(Qt::NoContextMenu);
        place_65->setIconSize(QSize(30, 30));
        place_65->setAutoDefault(false);
        place_95 = new QPushButton(PlacesWindow);
        place_95->setObjectName(QString::fromUtf8("place_95"));
        place_95->setGeometry(QRect(530, 360, 30, 30));
        place_95->setMinimumSize(QSize(30, 30));
        place_95->setMaximumSize(QSize(30, 30));
        place_95->setContextMenuPolicy(Qt::NoContextMenu);
        place_95->setIconSize(QSize(30, 30));
        place_95->setAutoDefault(false);
        place_33 = new QPushButton(PlacesWindow);
        place_33->setObjectName(QString::fromUtf8("place_33"));
        place_33->setGeometry(QRect(650, 160, 30, 30));
        place_33->setMinimumSize(QSize(30, 30));
        place_33->setMaximumSize(QSize(30, 30));
        place_33->setContextMenuPolicy(Qt::NoContextMenu);
        place_33->setIconSize(QSize(30, 30));
        place_33->setAutoDefault(false);
        place_79 = new QPushButton(PlacesWindow);
        place_79->setObjectName(QString::fromUtf8("place_79"));
        place_79->setGeometry(QRect(410, 320, 30, 30));
        place_79->setMinimumSize(QSize(30, 30));
        place_79->setMaximumSize(QSize(30, 30));
        place_79->setContextMenuPolicy(Qt::NoContextMenu);
        place_79->setIconSize(QSize(30, 30));
        place_79->setAutoDefault(false);
        place_87 = new QPushButton(PlacesWindow);
        place_87->setObjectName(QString::fromUtf8("place_87"));
        place_87->setGeometry(QRect(730, 320, 30, 30));
        place_87->setMinimumSize(QSize(30, 30));
        place_87->setMaximumSize(QSize(30, 30));
        place_87->setContextMenuPolicy(Qt::NoContextMenu);
        place_87->setIconSize(QSize(30, 30));
        place_87->setAutoDefault(false);
        place_63 = new QPushButton(PlacesWindow);
        place_63->setObjectName(QString::fromUtf8("place_63"));
        place_63->setGeometry(QRect(810, 240, 30, 30));
        place_63->setMinimumSize(QSize(30, 30));
        place_63->setMaximumSize(QSize(30, 30));
        place_63->setContextMenuPolicy(Qt::NoContextMenu);
        place_63->setIconSize(QSize(30, 30));
        place_63->setAutoDefault(false);
        place_103 = new QPushButton(PlacesWindow);
        place_103->setObjectName(QString::fromUtf8("place_103"));
        place_103->setGeometry(QRect(850, 360, 30, 30));
        place_103->setMinimumSize(QSize(30, 30));
        place_103->setMaximumSize(QSize(30, 30));
        place_103->setContextMenuPolicy(Qt::NoContextMenu);
        place_103->setIconSize(QSize(30, 30));
        place_103->setAutoDefault(false);
        place_92 = new QPushButton(PlacesWindow);
        place_92->setObjectName(QString::fromUtf8("place_92"));
        place_92->setGeometry(QRect(410, 360, 30, 30));
        place_92->setMinimumSize(QSize(30, 30));
        place_92->setMaximumSize(QSize(30, 30));
        place_92->setContextMenuPolicy(Qt::NoContextMenu);
        place_92->setIconSize(QSize(30, 30));
        place_92->setAutoDefault(false);
        place_68 = new QPushButton(PlacesWindow);
        place_68->setObjectName(QString::fromUtf8("place_68"));
        place_68->setGeometry(QRect(490, 280, 30, 30));
        place_68->setMinimumSize(QSize(30, 30));
        place_68->setMaximumSize(QSize(30, 30));
        place_68->setContextMenuPolicy(Qt::NoContextMenu);
        place_68->setIconSize(QSize(30, 30));
        place_68->setAutoDefault(false);
        place_108 = new QPushButton(PlacesWindow);
        place_108->setObjectName(QString::fromUtf8("place_108"));
        place_108->setGeometry(QRect(530, 400, 30, 30));
        place_108->setMinimumSize(QSize(30, 30));
        place_108->setMaximumSize(QSize(30, 30));
        place_108->setContextMenuPolicy(Qt::NoContextMenu);
        place_108->setIconSize(QSize(30, 30));
        place_108->setAutoDefault(false);
        place_116 = new QPushButton(PlacesWindow);
        place_116->setObjectName(QString::fromUtf8("place_116"));
        place_116->setGeometry(QRect(850, 400, 30, 30));
        place_116->setMinimumSize(QSize(30, 30));
        place_116->setMaximumSize(QSize(30, 30));
        place_116->setContextMenuPolicy(Qt::NoContextMenu);
        place_116->setIconSize(QSize(30, 30));
        place_116->setAutoDefault(false);
        place_31 = new QPushButton(PlacesWindow);
        place_31->setObjectName(QString::fromUtf8("place_31"));
        place_31->setGeometry(QRect(570, 160, 30, 30));
        place_31->setMinimumSize(QSize(30, 30));
        place_31->setMaximumSize(QSize(30, 30));
        place_31->setContextMenuPolicy(Qt::NoContextMenu);
        place_31->setIconSize(QSize(30, 30));
        place_31->setAutoDefault(false);
        place_21 = new QPushButton(PlacesWindow);
        place_21->setObjectName(QString::fromUtf8("place_21"));
        place_21->setGeometry(QRect(690, 120, 30, 30));
        place_21->setMinimumSize(QSize(30, 30));
        place_21->setMaximumSize(QSize(30, 30));
        place_21->setContextMenuPolicy(Qt::NoContextMenu);
        place_21->setIconSize(QSize(30, 30));
        place_21->setAutoDefault(false);
        place_121 = new QPushButton(PlacesWindow);
        place_121->setObjectName(QString::fromUtf8("place_121"));
        place_121->setGeometry(QRect(722, 440, 94, 51));
        place_121->setMinimumSize(QSize(94, 51));
        place_121->setMaximumSize(QSize(94, 51));
        place_121->setContextMenuPolicy(Qt::NoContextMenu);
        place_121->setIconSize(QSize(94, 51));
        place_121->setAutoDefault(false);
        place_77 = new QPushButton(PlacesWindow);
        place_77->setObjectName(QString::fromUtf8("place_77"));
        place_77->setGeometry(QRect(850, 280, 30, 30));
        place_77->setMinimumSize(QSize(30, 30));
        place_77->setMaximumSize(QSize(30, 30));
        place_77->setContextMenuPolicy(Qt::NoContextMenu);
        place_77->setIconSize(QSize(30, 30));
        place_77->setAutoDefault(false);
        place_98 = new QPushButton(PlacesWindow);
        place_98->setObjectName(QString::fromUtf8("place_98"));
        place_98->setGeometry(QRect(650, 360, 30, 30));
        place_98->setMinimumSize(QSize(30, 30));
        place_98->setMaximumSize(QSize(30, 30));
        place_98->setContextMenuPolicy(Qt::NoContextMenu);
        place_98->setIconSize(QSize(30, 30));
        place_98->setAutoDefault(false);
        place_104 = new QPushButton(PlacesWindow);
        place_104->setObjectName(QString::fromUtf8("place_104"));
        place_104->setGeometry(QRect(890, 360, 30, 30));
        place_104->setMinimumSize(QSize(30, 30));
        place_104->setMaximumSize(QSize(30, 30));
        place_104->setContextMenuPolicy(Qt::NoContextMenu);
        place_104->setIconSize(QSize(30, 30));
        place_104->setAutoDefault(false);
        place_82 = new QPushButton(PlacesWindow);
        place_82->setObjectName(QString::fromUtf8("place_82"));
        place_82->setGeometry(QRect(530, 320, 30, 30));
        place_82->setMinimumSize(QSize(30, 30));
        place_82->setMaximumSize(QSize(30, 30));
        place_82->setContextMenuPolicy(Qt::NoContextMenu);
        place_82->setIconSize(QSize(30, 30));
        place_82->setAutoDefault(false);
        place_90 = new QPushButton(PlacesWindow);
        place_90->setObjectName(QString::fromUtf8("place_90"));
        place_90->setGeometry(QRect(850, 320, 30, 30));
        place_90->setMinimumSize(QSize(30, 30));
        place_90->setMaximumSize(QSize(30, 30));
        place_90->setContextMenuPolicy(Qt::NoContextMenu);
        place_90->setIconSize(QSize(30, 30));
        place_90->setAutoDefault(false);
        place_106 = new QPushButton(PlacesWindow);
        place_106->setObjectName(QString::fromUtf8("place_106"));
        place_106->setGeometry(QRect(450, 400, 30, 30));
        place_106->setMinimumSize(QSize(30, 30));
        place_106->setMaximumSize(QSize(30, 30));
        place_106->setContextMenuPolicy(Qt::NoContextMenu);
        place_106->setIconSize(QSize(30, 30));
        place_106->setAutoDefault(false);
        place_19 = new QPushButton(PlacesWindow);
        place_19->setObjectName(QString::fromUtf8("place_19"));
        place_19->setGeometry(QRect(610, 120, 30, 30));
        place_19->setMinimumSize(QSize(30, 30));
        place_19->setMaximumSize(QSize(30, 30));
        place_19->setContextMenuPolicy(Qt::NoContextMenu);
        place_19->setIconSize(QSize(30, 30));
        place_19->setAutoDefault(false);
        place_38 = new QPushButton(PlacesWindow);
        place_38->setObjectName(QString::fromUtf8("place_38"));
        place_38->setGeometry(QRect(850, 160, 30, 30));
        place_38->setMinimumSize(QSize(30, 30));
        place_38->setMaximumSize(QSize(30, 30));
        place_38->setContextMenuPolicy(Qt::NoContextMenu);
        place_38->setIconSize(QSize(30, 30));
        place_38->setAutoDefault(false);
        place_52 = new QPushButton(PlacesWindow);
        place_52->setObjectName(QString::fromUtf8("place_52"));
        place_52->setGeometry(QRect(890, 200, 30, 30));
        place_52->setMinimumSize(QSize(30, 30));
        place_52->setMaximumSize(QSize(30, 30));
        place_52->setContextMenuPolicy(Qt::NoContextMenu);
        place_52->setIconSize(QSize(30, 30));
        place_52->setAutoDefault(false);
        place_24 = new QPushButton(PlacesWindow);
        place_24->setObjectName(QString::fromUtf8("place_24"));
        place_24->setGeometry(QRect(810, 120, 30, 30));
        place_24->setMinimumSize(QSize(30, 30));
        place_24->setMaximumSize(QSize(30, 30));
        place_24->setContextMenuPolicy(Qt::NoContextMenu);
        place_24->setIconSize(QSize(30, 30));
        place_24->setAutoDefault(false);
        place_48 = new QPushButton(PlacesWindow);
        place_48->setObjectName(QString::fromUtf8("place_48"));
        place_48->setGeometry(QRect(730, 200, 30, 30));
        place_48->setMinimumSize(QSize(30, 30));
        place_48->setMaximumSize(QSize(30, 30));
        place_48->setContextMenuPolicy(Qt::NoContextMenu);
        place_48->setIconSize(QSize(30, 30));
        place_48->setAutoDefault(false);
        place_36 = new QPushButton(PlacesWindow);
        place_36->setObjectName(QString::fromUtf8("place_36"));
        place_36->setGeometry(QRect(770, 160, 30, 30));
        place_36->setMinimumSize(QSize(30, 30));
        place_36->setMaximumSize(QSize(30, 30));
        place_36->setContextMenuPolicy(Qt::NoContextMenu);
        place_36->setIconSize(QSize(30, 30));
        place_36->setAutoDefault(false);
        place_53 = new QPushButton(PlacesWindow);
        place_53->setObjectName(QString::fromUtf8("place_53"));
        place_53->setGeometry(QRect(410, 240, 30, 30));
        place_53->setMinimumSize(QSize(30, 30));
        place_53->setMaximumSize(QSize(30, 30));
        place_53->setContextMenuPolicy(Qt::NoContextMenu);
        place_53->setIconSize(QSize(30, 30));
        place_53->setAutoDefault(false);
        place_12 = new QPushButton(PlacesWindow);
        place_12->setObjectName(QString::fromUtf8("place_12"));
        place_12->setGeometry(QRect(850, 80, 30, 30));
        place_12->setMinimumSize(QSize(30, 30));
        place_12->setMaximumSize(QSize(30, 30));
        place_12->setContextMenuPolicy(Qt::NoContextMenu);
        place_12->setIconSize(QSize(30, 30));
        place_12->setAutoDefault(false);
        place_4 = new QPushButton(PlacesWindow);
        place_4->setObjectName(QString::fromUtf8("place_4"));
        place_4->setGeometry(QRect(530, 80, 30, 30));
        place_4->setMinimumSize(QSize(30, 30));
        place_4->setMaximumSize(QSize(30, 30));
        place_4->setContextMenuPolicy(Qt::NoContextMenu);
        place_4->setIconSize(QSize(30, 30));
        place_4->setAutoDefault(false);
        place_81 = new QPushButton(PlacesWindow);
        place_81->setObjectName(QString::fromUtf8("place_81"));
        place_81->setGeometry(QRect(490, 320, 30, 30));
        place_81->setMinimumSize(QSize(30, 30));
        place_81->setMaximumSize(QSize(30, 30));
        place_81->setContextMenuPolicy(Qt::NoContextMenu);
        place_81->setIconSize(QSize(30, 30));
        place_81->setAutoDefault(false);
        place_7 = new QPushButton(PlacesWindow);
        place_7->setObjectName(QString::fromUtf8("place_7"));
        place_7->setGeometry(QRect(650, 80, 30, 30));
        place_7->setMinimumSize(QSize(30, 30));
        place_7->setMaximumSize(QSize(30, 30));
        place_7->setContextMenuPolicy(Qt::NoContextMenu);
        place_7->setIconSize(QSize(30, 30));
        place_7->setAutoDefault(false);
        place_86 = new QPushButton(PlacesWindow);
        place_86->setObjectName(QString::fromUtf8("place_86"));
        place_86->setGeometry(QRect(690, 320, 30, 30));
        place_86->setMinimumSize(QSize(30, 30));
        place_86->setMaximumSize(QSize(30, 30));
        place_86->setContextMenuPolicy(Qt::NoContextMenu);
        place_86->setIconSize(QSize(30, 30));
        place_86->setAutoDefault(false);
        place_94 = new QPushButton(PlacesWindow);
        place_94->setObjectName(QString::fromUtf8("place_94"));
        place_94->setGeometry(QRect(490, 360, 30, 30));
        place_94->setMinimumSize(QSize(30, 30));
        place_94->setMaximumSize(QSize(30, 30));
        place_94->setContextMenuPolicy(Qt::NoContextMenu);
        place_94->setIconSize(QSize(30, 30));
        place_94->setAutoDefault(false);
        place_70 = new QPushButton(PlacesWindow);
        place_70->setObjectName(QString::fromUtf8("place_70"));
        place_70->setGeometry(QRect(570, 280, 30, 30));
        place_70->setMinimumSize(QSize(30, 30));
        place_70->setMaximumSize(QSize(30, 30));
        place_70->setContextMenuPolicy(Qt::NoContextMenu);
        place_70->setIconSize(QSize(30, 30));
        place_70->setAutoDefault(false);
        place_110 = new QPushButton(PlacesWindow);
        place_110->setObjectName(QString::fromUtf8("place_110"));
        place_110->setGeometry(QRect(610, 400, 30, 30));
        place_110->setMinimumSize(QSize(30, 30));
        place_110->setMaximumSize(QSize(30, 30));
        place_110->setContextMenuPolicy(Qt::NoContextMenu);
        place_110->setIconSize(QSize(30, 30));
        place_110->setAutoDefault(false);
        place_8 = new QPushButton(PlacesWindow);
        place_8->setObjectName(QString::fromUtf8("place_8"));
        place_8->setGeometry(QRect(690, 80, 30, 30));
        place_8->setMinimumSize(QSize(30, 30));
        place_8->setMaximumSize(QSize(30, 30));
        place_8->setContextMenuPolicy(Qt::NoContextMenu);
        place_8->setIconSize(QSize(30, 30));
        place_8->setAutoDefault(false);
        place_115 = new QPushButton(PlacesWindow);
        place_115->setObjectName(QString::fromUtf8("place_115"));
        place_115->setGeometry(QRect(810, 400, 30, 30));
        place_115->setMinimumSize(QSize(30, 30));
        place_115->setMaximumSize(QSize(30, 30));
        place_115->setContextMenuPolicy(Qt::NoContextMenu);
        place_115->setIconSize(QSize(30, 30));
        place_115->setAutoDefault(false);
        place_30 = new QPushButton(PlacesWindow);
        place_30->setObjectName(QString::fromUtf8("place_30"));
        place_30->setGeometry(QRect(530, 160, 30, 30));
        place_30->setMinimumSize(QSize(30, 30));
        place_30->setMaximumSize(QSize(30, 30));
        place_30->setContextMenuPolicy(Qt::NoContextMenu);
        place_30->setIconSize(QSize(30, 30));
        place_30->setAutoDefault(false);
        place_40 = new QPushButton(PlacesWindow);
        place_40->setObjectName(QString::fromUtf8("place_40"));
        place_40->setGeometry(QRect(410, 200, 30, 30));
        place_40->setMinimumSize(QSize(30, 30));
        place_40->setMaximumSize(QSize(30, 30));
        place_40->setContextMenuPolicy(Qt::NoContextMenu);
        place_40->setIconSize(QSize(30, 30));
        place_40->setAutoDefault(false);
        place_84 = new QPushButton(PlacesWindow);
        place_84->setObjectName(QString::fromUtf8("place_84"));
        place_84->setGeometry(QRect(610, 320, 30, 30));
        place_84->setMinimumSize(QSize(30, 30));
        place_84->setMaximumSize(QSize(30, 30));
        place_84->setContextMenuPolicy(Qt::NoContextMenu);
        place_84->setIconSize(QSize(30, 30));
        place_84->setAutoDefault(false);
        place_9 = new QPushButton(PlacesWindow);
        place_9->setObjectName(QString::fromUtf8("place_9"));
        place_9->setGeometry(QRect(730, 80, 30, 30));
        place_9->setMinimumSize(QSize(30, 30));
        place_9->setMaximumSize(QSize(30, 30));
        place_9->setContextMenuPolicy(Qt::NoContextMenu);
        place_9->setIconSize(QSize(30, 30));
        place_9->setAutoDefault(false);
        place_111 = new QPushButton(PlacesWindow);
        place_111->setObjectName(QString::fromUtf8("place_111"));
        place_111->setGeometry(QRect(650, 400, 30, 30));
        place_111->setMinimumSize(QSize(30, 30));
        place_111->setMaximumSize(QSize(30, 30));
        place_111->setContextMenuPolicy(Qt::NoContextMenu);
        place_111->setIconSize(QSize(30, 30));
        place_111->setAutoDefault(false);
        place_57 = new QPushButton(PlacesWindow);
        place_57->setObjectName(QString::fromUtf8("place_57"));
        place_57->setGeometry(QRect(570, 240, 30, 30));
        place_57->setMinimumSize(QSize(30, 30));
        place_57->setMaximumSize(QSize(30, 30));
        place_57->setContextMenuPolicy(Qt::NoContextMenu);
        place_57->setIconSize(QSize(30, 30));
        place_57->setAutoDefault(false);
        place_113 = new QPushButton(PlacesWindow);
        place_113->setObjectName(QString::fromUtf8("place_113"));
        place_113->setGeometry(QRect(730, 400, 30, 30));
        place_113->setMinimumSize(QSize(30, 30));
        place_113->setMaximumSize(QSize(30, 30));
        place_113->setContextMenuPolicy(Qt::NoContextMenu);
        place_113->setIconSize(QSize(30, 30));
        place_113->setAutoDefault(false);
        place_26 = new QPushButton(PlacesWindow);
        place_26->setObjectName(QString::fromUtf8("place_26"));
        place_26->setGeometry(QRect(890, 120, 30, 30));
        place_26->setMinimumSize(QSize(30, 30));
        place_26->setMaximumSize(QSize(30, 30));
        place_26->setContextMenuPolicy(Qt::NoContextMenu);
        place_26->setIconSize(QSize(30, 30));
        place_26->setAutoDefault(false);
        place_59 = new QPushButton(PlacesWindow);
        place_59->setObjectName(QString::fromUtf8("place_59"));
        place_59->setGeometry(QRect(650, 240, 30, 30));
        place_59->setMinimumSize(QSize(30, 30));
        place_59->setMaximumSize(QSize(30, 30));
        place_59->setContextMenuPolicy(Qt::NoContextMenu);
        place_59->setIconSize(QSize(30, 30));
        place_59->setAutoDefault(false);
        place_71 = new QPushButton(PlacesWindow);
        place_71->setObjectName(QString::fromUtf8("place_71"));
        place_71->setGeometry(QRect(610, 280, 30, 30));
        place_71->setMinimumSize(QSize(30, 30));
        place_71->setMaximumSize(QSize(30, 30));
        place_71->setContextMenuPolicy(Qt::NoContextMenu);
        place_71->setIconSize(QSize(30, 30));
        place_71->setAutoDefault(false);
        place_47 = new QPushButton(PlacesWindow);
        place_47->setObjectName(QString::fromUtf8("place_47"));
        place_47->setGeometry(QRect(690, 200, 30, 30));
        place_47->setMinimumSize(QSize(30, 30));
        place_47->setMaximumSize(QSize(30, 30));
        place_47->setContextMenuPolicy(Qt::NoContextMenu);
        place_47->setIconSize(QSize(30, 30));
        place_47->setAutoDefault(false);
        place_55 = new QPushButton(PlacesWindow);
        place_55->setObjectName(QString::fromUtf8("place_55"));
        place_55->setGeometry(QRect(490, 240, 30, 30));
        place_55->setMinimumSize(QSize(30, 30));
        place_55->setMaximumSize(QSize(30, 30));
        place_55->setContextMenuPolicy(Qt::NoContextMenu);
        place_55->setIconSize(QSize(30, 30));
        place_55->setAutoDefault(false);
        place_29 = new QPushButton(PlacesWindow);
        place_29->setObjectName(QString::fromUtf8("place_29"));
        place_29->setGeometry(QRect(490, 160, 30, 30));
        place_29->setMinimumSize(QSize(30, 30));
        place_29->setMaximumSize(QSize(30, 30));
        place_29->setContextMenuPolicy(Qt::NoContextMenu);
        place_29->setIconSize(QSize(30, 30));
        place_29->setAutoDefault(false);
        place_37 = new QPushButton(PlacesWindow);
        place_37->setObjectName(QString::fromUtf8("place_37"));
        place_37->setGeometry(QRect(810, 160, 30, 30));
        place_37->setMinimumSize(QSize(30, 30));
        place_37->setMaximumSize(QSize(30, 30));
        place_37->setContextMenuPolicy(Qt::NoContextMenu);
        place_37->setIconSize(QSize(30, 30));
        place_37->setAutoDefault(false);
        place_60 = new QPushButton(PlacesWindow);
        place_60->setObjectName(QString::fromUtf8("place_60"));
        place_60->setGeometry(QRect(690, 240, 30, 30));
        place_60->setMinimumSize(QSize(30, 30));
        place_60->setMaximumSize(QSize(30, 30));
        place_60->setContextMenuPolicy(Qt::NoContextMenu);
        place_60->setIconSize(QSize(30, 30));
        place_60->setAutoDefault(false);
        place_100 = new QPushButton(PlacesWindow);
        place_100->setObjectName(QString::fromUtf8("place_100"));
        place_100->setGeometry(QRect(730, 360, 30, 30));
        place_100->setMinimumSize(QSize(30, 30));
        place_100->setMaximumSize(QSize(30, 30));
        place_100->setContextMenuPolicy(Qt::NoContextMenu);
        place_100->setIconSize(QSize(30, 30));
        place_100->setAutoDefault(false);
        place_34 = new QPushButton(PlacesWindow);
        place_34->setObjectName(QString::fromUtf8("place_34"));
        place_34->setGeometry(QRect(690, 160, 30, 30));
        place_34->setMinimumSize(QSize(30, 30));
        place_34->setMaximumSize(QSize(30, 30));
        place_34->setContextMenuPolicy(Qt::NoContextMenu);
        place_34->setIconSize(QSize(30, 30));
        place_34->setAutoDefault(false);
        place_13 = new QPushButton(PlacesWindow);
        place_13->setObjectName(QString::fromUtf8("place_13"));
        place_13->setGeometry(QRect(890, 80, 30, 30));
        place_13->setMinimumSize(QSize(30, 30));
        place_13->setMaximumSize(QSize(30, 30));
        place_13->setContextMenuPolicy(Qt::NoContextMenu);
        place_13->setIconSize(QSize(30, 30));
        place_13->setAutoDefault(false);
        place_96 = new QPushButton(PlacesWindow);
        place_96->setObjectName(QString::fromUtf8("place_96"));
        place_96->setGeometry(QRect(570, 360, 30, 30));
        place_96->setMinimumSize(QSize(30, 30));
        place_96->setMaximumSize(QSize(30, 30));
        place_96->setContextMenuPolicy(Qt::NoContextMenu);
        place_96->setIconSize(QSize(30, 30));
        place_96->setAutoDefault(false);
        place_15 = new QPushButton(PlacesWindow);
        place_15->setObjectName(QString::fromUtf8("place_15"));
        place_15->setGeometry(QRect(450, 120, 30, 30));
        place_15->setMinimumSize(QSize(30, 30));
        place_15->setMaximumSize(QSize(30, 30));
        place_15->setContextMenuPolicy(Qt::NoContextMenu);
        place_15->setIconSize(QSize(30, 30));
        place_15->setAutoDefault(false);
        place_88 = new QPushButton(PlacesWindow);
        place_88->setObjectName(QString::fromUtf8("place_88"));
        place_88->setGeometry(QRect(770, 320, 30, 30));
        place_88->setMinimumSize(QSize(30, 30));
        place_88->setMaximumSize(QSize(30, 30));
        place_88->setContextMenuPolicy(Qt::NoContextMenu);
        place_88->setIconSize(QSize(30, 30));
        place_88->setAutoDefault(false);
        place_74 = new QPushButton(PlacesWindow);
        place_74->setObjectName(QString::fromUtf8("place_74"));
        place_74->setGeometry(QRect(730, 280, 30, 30));
        place_74->setMinimumSize(QSize(30, 30));
        place_74->setMaximumSize(QSize(30, 30));
        place_74->setContextMenuPolicy(Qt::NoContextMenu);
        place_74->setIconSize(QSize(30, 30));
        place_74->setAutoDefault(false);
        place_35 = new QPushButton(PlacesWindow);
        place_35->setObjectName(QString::fromUtf8("place_35"));
        place_35->setGeometry(QRect(730, 160, 30, 30));
        place_35->setMinimumSize(QSize(30, 30));
        place_35->setMaximumSize(QSize(30, 30));
        place_35->setContextMenuPolicy(Qt::NoContextMenu);
        place_35->setIconSize(QSize(30, 30));
        place_35->setAutoDefault(false);
        place_93 = new QPushButton(PlacesWindow);
        place_93->setObjectName(QString::fromUtf8("place_93"));
        place_93->setGeometry(QRect(450, 360, 30, 30));
        place_93->setMinimumSize(QSize(30, 30));
        place_93->setMaximumSize(QSize(30, 30));
        place_93->setContextMenuPolicy(Qt::NoContextMenu);
        place_93->setIconSize(QSize(30, 30));
        place_93->setAutoDefault(false);
        place_97 = new QPushButton(PlacesWindow);
        place_97->setObjectName(QString::fromUtf8("place_97"));
        place_97->setGeometry(QRect(610, 360, 30, 30));
        place_97->setMinimumSize(QSize(30, 30));
        place_97->setMaximumSize(QSize(30, 30));
        place_97->setContextMenuPolicy(Qt::NoContextMenu);
        place_97->setIconSize(QSize(30, 30));
        place_97->setAutoDefault(false);
        place_117 = new QPushButton(PlacesWindow);
        place_117->setObjectName(QString::fromUtf8("place_117"));
        place_117->setGeometry(QRect(890, 400, 30, 30));
        place_117->setMinimumSize(QSize(30, 30));
        place_117->setMaximumSize(QSize(30, 30));
        place_117->setContextMenuPolicy(Qt::NoContextMenu);
        place_117->setIconSize(QSize(30, 30));
        place_117->setAutoDefault(false);
        place_32 = new QPushButton(PlacesWindow);
        place_32->setObjectName(QString::fromUtf8("place_32"));
        place_32->setGeometry(QRect(610, 160, 30, 30));
        place_32->setMinimumSize(QSize(30, 30));
        place_32->setMaximumSize(QSize(30, 30));
        place_32->setContextMenuPolicy(Qt::NoContextMenu);
        place_32->setIconSize(QSize(30, 30));
        place_32->setAutoDefault(false);
        place_44 = new QPushButton(PlacesWindow);
        place_44->setObjectName(QString::fromUtf8("place_44"));
        place_44->setGeometry(QRect(570, 200, 30, 30));
        place_44->setMinimumSize(QSize(30, 30));
        place_44->setMaximumSize(QSize(30, 30));
        place_44->setContextMenuPolicy(Qt::NoContextMenu);
        place_44->setIconSize(QSize(30, 30));
        place_44->setAutoDefault(false);
        place_122 = new QPushButton(PlacesWindow);
        place_122->setObjectName(QString::fromUtf8("place_122"));
        place_122->setGeometry(QRect(826, 440, 94, 51));
        place_122->setMinimumSize(QSize(94, 51));
        place_122->setMaximumSize(QSize(94, 51));
        place_122->setContextMenuPolicy(Qt::NoContextMenu);
        place_122->setIconSize(QSize(94, 51));
        place_122->setAutoDefault(false);
        place_16 = new QPushButton(PlacesWindow);
        place_16->setObjectName(QString::fromUtf8("place_16"));
        place_16->setGeometry(QRect(490, 120, 30, 30));
        place_16->setMinimumSize(QSize(30, 30));
        place_16->setMaximumSize(QSize(30, 30));
        place_16->setContextMenuPolicy(Qt::NoContextMenu);
        place_16->setIconSize(QSize(30, 30));
        place_16->setAutoDefault(false);
        place_89 = new QPushButton(PlacesWindow);
        place_89->setObjectName(QString::fromUtf8("place_89"));
        place_89->setGeometry(QRect(810, 320, 30, 30));
        place_89->setMinimumSize(QSize(30, 30));
        place_89->setMaximumSize(QSize(30, 30));
        place_89->setContextMenuPolicy(Qt::NoContextMenu);
        place_89->setIconSize(QSize(30, 30));
        place_89->setAutoDefault(false);
        place_99 = new QPushButton(PlacesWindow);
        place_99->setObjectName(QString::fromUtf8("place_99"));
        place_99->setGeometry(QRect(690, 360, 30, 30));
        place_99->setMinimumSize(QSize(30, 30));
        place_99->setMaximumSize(QSize(30, 30));
        place_99->setContextMenuPolicy(Qt::NoContextMenu);
        place_99->setIconSize(QSize(30, 30));
        place_99->setAutoDefault(false);
        place_6 = new QPushButton(PlacesWindow);
        place_6->setObjectName(QString::fromUtf8("place_6"));
        place_6->setGeometry(QRect(610, 80, 30, 30));
        place_6->setMinimumSize(QSize(30, 30));
        place_6->setMaximumSize(QSize(30, 30));
        place_6->setContextMenuPolicy(Qt::NoContextMenu);
        place_6->setIconSize(QSize(30, 30));
        place_6->setAutoDefault(false);
        place_91 = new QPushButton(PlacesWindow);
        place_91->setObjectName(QString::fromUtf8("place_91"));
        place_91->setGeometry(QRect(890, 320, 30, 30));
        place_91->setMinimumSize(QSize(30, 30));
        place_91->setMaximumSize(QSize(30, 30));
        place_91->setContextMenuPolicy(Qt::NoContextMenu);
        place_91->setIconSize(QSize(30, 30));
        place_91->setAutoDefault(false);
        place_118 = new QPushButton(PlacesWindow);
        place_118->setObjectName(QString::fromUtf8("place_118"));
        place_118->setGeometry(QRect(410, 440, 94, 51));
        place_118->setMinimumSize(QSize(94, 51));
        place_118->setMaximumSize(QSize(94, 51));
        place_118->setContextMenuPolicy(Qt::NoContextMenu);
        place_118->setIconSize(QSize(94, 51));
        place_118->setAutoDefault(false);
        place_64 = new QPushButton(PlacesWindow);
        place_64->setObjectName(QString::fromUtf8("place_64"));
        place_64->setGeometry(QRect(850, 240, 30, 30));
        place_64->setMinimumSize(QSize(30, 30));
        place_64->setMaximumSize(QSize(30, 30));
        place_64->setContextMenuPolicy(Qt::NoContextMenu);
        place_64->setIconSize(QSize(30, 30));
        place_64->setAutoDefault(false);
        place_1 = new QPushButton(PlacesWindow);
        place_1->setObjectName(QString::fromUtf8("place_1"));
        place_1->setGeometry(QRect(410, 80, 30, 30));
        place_1->setMinimumSize(QSize(30, 30));
        place_1->setMaximumSize(QSize(30, 30));
        place_1->setContextMenuPolicy(Qt::NoContextMenu);
        place_1->setIconSize(QSize(30, 30));
        place_1->setAutoDefault(false);
        place_66 = new QPushButton(PlacesWindow);
        place_66->setObjectName(QString::fromUtf8("place_66"));
        place_66->setGeometry(QRect(410, 280, 30, 30));
        place_66->setMinimumSize(QSize(30, 30));
        place_66->setMaximumSize(QSize(30, 30));
        place_66->setContextMenuPolicy(Qt::NoContextMenu);
        place_66->setIconSize(QSize(30, 30));
        place_66->setAutoDefault(false);
        place_28 = new QPushButton(PlacesWindow);
        place_28->setObjectName(QString::fromUtf8("place_28"));
        place_28->setGeometry(QRect(450, 160, 30, 30));
        place_28->setMinimumSize(QSize(30, 30));
        place_28->setMaximumSize(QSize(30, 30));
        place_28->setContextMenuPolicy(Qt::NoContextMenu);
        place_28->setIconSize(QSize(30, 30));
        place_28->setAutoDefault(false);
        place_73 = new QPushButton(PlacesWindow);
        place_73->setObjectName(QString::fromUtf8("place_73"));
        place_73->setGeometry(QRect(690, 280, 30, 30));
        place_73->setMinimumSize(QSize(30, 30));
        place_73->setMaximumSize(QSize(30, 30));
        place_73->setContextMenuPolicy(Qt::NoContextMenu);
        place_73->setIconSize(QSize(30, 30));
        place_73->setAutoDefault(false);
        place_49 = new QPushButton(PlacesWindow);
        place_49->setObjectName(QString::fromUtf8("place_49"));
        place_49->setGeometry(QRect(770, 200, 30, 30));
        place_49->setMinimumSize(QSize(30, 30));
        place_49->setMaximumSize(QSize(30, 30));
        place_49->setContextMenuPolicy(Qt::NoContextMenu);
        place_49->setIconSize(QSize(30, 30));
        place_49->setAutoDefault(false);
        place_78 = new QPushButton(PlacesWindow);
        place_78->setObjectName(QString::fromUtf8("place_78"));
        place_78->setGeometry(QRect(890, 280, 30, 30));
        place_78->setMinimumSize(QSize(30, 30));
        place_78->setMaximumSize(QSize(30, 30));
        place_78->setContextMenuPolicy(Qt::NoContextMenu);
        place_78->setIconSize(QSize(30, 30));
        place_78->setAutoDefault(false);
        place_39 = new QPushButton(PlacesWindow);
        place_39->setObjectName(QString::fromUtf8("place_39"));
        place_39->setGeometry(QRect(890, 160, 30, 30));
        place_39->setMinimumSize(QSize(30, 30));
        place_39->setMaximumSize(QSize(30, 30));
        place_39->setContextMenuPolicy(Qt::NoContextMenu);
        place_39->setIconSize(QSize(30, 30));
        place_39->setAutoDefault(false);
        place_54 = new QPushButton(PlacesWindow);
        place_54->setObjectName(QString::fromUtf8("place_54"));
        place_54->setGeometry(QRect(450, 240, 30, 30));
        place_54->setMinimumSize(QSize(30, 30));
        place_54->setMaximumSize(QSize(30, 30));
        place_54->setContextMenuPolicy(Qt::NoContextMenu);
        place_54->setIconSize(QSize(30, 30));
        place_54->setAutoDefault(false);
        place_3 = new QPushButton(PlacesWindow);
        place_3->setObjectName(QString::fromUtf8("place_3"));
        place_3->setGeometry(QRect(490, 80, 30, 30));
        place_3->setMinimumSize(QSize(30, 30));
        place_3->setMaximumSize(QSize(30, 30));
        place_3->setContextMenuPolicy(Qt::NoContextMenu);
        place_3->setIconSize(QSize(30, 30));
        place_3->setAutoDefault(false);
        place_62 = new QPushButton(PlacesWindow);
        place_62->setObjectName(QString::fromUtf8("place_62"));
        place_62->setGeometry(QRect(770, 240, 30, 30));
        place_62->setMinimumSize(QSize(30, 30));
        place_62->setMaximumSize(QSize(30, 30));
        place_62->setContextMenuPolicy(Qt::NoContextMenu);
        place_62->setIconSize(QSize(30, 30));
        place_62->setAutoDefault(false);
        place_102 = new QPushButton(PlacesWindow);
        place_102->setObjectName(QString::fromUtf8("place_102"));
        place_102->setGeometry(QRect(810, 360, 30, 30));
        place_102->setMinimumSize(QSize(30, 30));
        place_102->setMaximumSize(QSize(30, 30));
        place_102->setContextMenuPolicy(Qt::NoContextMenu);
        place_102->setIconSize(QSize(30, 30));
        place_102->setAutoDefault(false);
        place_67 = new QPushButton(PlacesWindow);
        place_67->setObjectName(QString::fromUtf8("place_67"));
        place_67->setGeometry(QRect(450, 280, 30, 30));
        place_67->setMinimumSize(QSize(30, 30));
        place_67->setMaximumSize(QSize(30, 30));
        place_67->setContextMenuPolicy(Qt::NoContextMenu);
        place_67->setIconSize(QSize(30, 30));
        place_67->setAutoDefault(false);
        place_107 = new QPushButton(PlacesWindow);
        place_107->setObjectName(QString::fromUtf8("place_107"));
        place_107->setGeometry(QRect(490, 400, 30, 30));
        place_107->setMinimumSize(QSize(30, 30));
        place_107->setMaximumSize(QSize(30, 30));
        place_107->setContextMenuPolicy(Qt::NoContextMenu);
        place_107->setIconSize(QSize(30, 30));
        place_107->setAutoDefault(false);
        place_20 = new QPushButton(PlacesWindow);
        place_20->setObjectName(QString::fromUtf8("place_20"));
        place_20->setGeometry(QRect(650, 120, 30, 30));
        place_20->setMinimumSize(QSize(30, 30));
        place_20->setMaximumSize(QSize(30, 30));
        place_20->setContextMenuPolicy(Qt::NoContextMenu);
        place_20->setIconSize(QSize(30, 30));
        place_20->setAutoDefault(false);
        place_76 = new QPushButton(PlacesWindow);
        place_76->setObjectName(QString::fromUtf8("place_76"));
        place_76->setGeometry(QRect(810, 280, 30, 30));
        place_76->setMinimumSize(QSize(30, 30));
        place_76->setMaximumSize(QSize(30, 30));
        place_76->setContextMenuPolicy(Qt::NoContextMenu);
        place_76->setIconSize(QSize(30, 30));
        place_76->setAutoDefault(false);
        place_42 = new QPushButton(PlacesWindow);
        place_42->setObjectName(QString::fromUtf8("place_42"));
        place_42->setGeometry(QRect(490, 200, 30, 30));
        place_42->setMinimumSize(QSize(30, 30));
        place_42->setMaximumSize(QSize(30, 30));
        place_42->setContextMenuPolicy(Qt::NoContextMenu);
        place_42->setIconSize(QSize(30, 30));
        place_42->setAutoDefault(false);
        place_105 = new QPushButton(PlacesWindow);
        place_105->setObjectName(QString::fromUtf8("place_105"));
        place_105->setGeometry(QRect(410, 400, 30, 30));
        place_105->setMinimumSize(QSize(30, 30));
        place_105->setMaximumSize(QSize(30, 30));
        place_105->setContextMenuPolicy(Qt::NoContextMenu);
        place_105->setIconSize(QSize(30, 30));
        place_105->setAutoDefault(false);
        place_41 = new QPushButton(PlacesWindow);
        place_41->setObjectName(QString::fromUtf8("place_41"));
        place_41->setGeometry(QRect(450, 200, 30, 30));
        place_41->setMinimumSize(QSize(30, 30));
        place_41->setMaximumSize(QSize(30, 30));
        place_41->setContextMenuPolicy(Qt::NoContextMenu);
        place_41->setIconSize(QSize(30, 30));
        place_41->setAutoDefault(false);
        place_43 = new QPushButton(PlacesWindow);
        place_43->setObjectName(QString::fromUtf8("place_43"));
        place_43->setGeometry(QRect(530, 200, 30, 30));
        place_43->setMinimumSize(QSize(30, 30));
        place_43->setMaximumSize(QSize(30, 30));
        place_43->setContextMenuPolicy(Qt::NoContextMenu);
        place_43->setIconSize(QSize(30, 30));
        place_43->setAutoDefault(false);
        place_18 = new QPushButton(PlacesWindow);
        place_18->setObjectName(QString::fromUtf8("place_18"));
        place_18->setGeometry(QRect(570, 120, 30, 30));
        place_18->setMinimumSize(QSize(30, 30));
        place_18->setMaximumSize(QSize(30, 30));
        place_18->setContextMenuPolicy(Qt::NoContextMenu);
        place_18->setIconSize(QSize(30, 30));
        place_18->setAutoDefault(false);
        place_51 = new QPushButton(PlacesWindow);
        place_51->setObjectName(QString::fromUtf8("place_51"));
        place_51->setGeometry(QRect(850, 200, 30, 30));
        place_51->setMinimumSize(QSize(30, 30));
        place_51->setMaximumSize(QSize(30, 30));
        place_51->setContextMenuPolicy(Qt::NoContextMenu);
        place_51->setIconSize(QSize(30, 30));
        place_51->setAutoDefault(false);
        place_23 = new QPushButton(PlacesWindow);
        place_23->setObjectName(QString::fromUtf8("place_23"));
        place_23->setGeometry(QRect(770, 120, 30, 30));
        place_23->setMinimumSize(QSize(30, 30));
        place_23->setMaximumSize(QSize(30, 30));
        place_23->setContextMenuPolicy(Qt::NoContextMenu);
        place_23->setIconSize(QSize(30, 30));
        place_23->setAutoDefault(false);
        place_112 = new QPushButton(PlacesWindow);
        place_112->setObjectName(QString::fromUtf8("place_112"));
        place_112->setGeometry(QRect(690, 400, 30, 30));
        place_112->setMinimumSize(QSize(30, 30));
        place_112->setMaximumSize(QSize(30, 30));
        place_112->setContextMenuPolicy(Qt::NoContextMenu);
        place_112->setIconSize(QSize(30, 30));
        place_112->setAutoDefault(false);
        place_11 = new QPushButton(PlacesWindow);
        place_11->setObjectName(QString::fromUtf8("place_11"));
        place_11->setGeometry(QRect(810, 80, 30, 30));
        place_11->setMinimumSize(QSize(30, 30));
        place_11->setMaximumSize(QSize(30, 30));
        place_11->setContextMenuPolicy(Qt::NoContextMenu);
        place_11->setIconSize(QSize(30, 30));
        place_11->setAutoDefault(false);
        place_120 = new QPushButton(PlacesWindow);
        place_120->setObjectName(QString::fromUtf8("place_120"));
        place_120->setGeometry(QRect(618, 440, 94, 51));
        place_120->setMinimumSize(QSize(94, 51));
        place_120->setMaximumSize(QSize(94, 51));
        place_120->setContextMenuPolicy(Qt::NoContextMenu);
        place_120->setIconSize(QSize(94, 51));
        place_120->setAutoDefault(false);
        place_5 = new QPushButton(PlacesWindow);
        place_5->setObjectName(QString::fromUtf8("place_5"));
        place_5->setGeometry(QRect(570, 80, 30, 30));
        place_5->setMinimumSize(QSize(30, 30));
        place_5->setMaximumSize(QSize(30, 30));
        place_5->setContextMenuPolicy(Qt::NoContextMenu);
        place_5->setIconSize(QSize(30, 30));
        place_5->setAutoDefault(false);
        place_10 = new QPushButton(PlacesWindow);
        place_10->setObjectName(QString::fromUtf8("place_10"));
        place_10->setGeometry(QRect(770, 80, 30, 30));
        place_10->setMinimumSize(QSize(30, 30));
        place_10->setMaximumSize(QSize(30, 30));
        place_10->setContextMenuPolicy(Qt::NoContextMenu);
        place_10->setIconSize(QSize(30, 30));
        place_10->setAutoDefault(false);
        place_2 = new QPushButton(PlacesWindow);
        place_2->setObjectName(QString::fromUtf8("place_2"));
        place_2->setGeometry(QRect(450, 80, 30, 30));
        place_2->setMinimumSize(QSize(30, 30));
        place_2->setMaximumSize(QSize(30, 30));
        place_2->setContextMenuPolicy(Qt::NoContextMenu);
        place_2->setIconSize(QSize(30, 30));
        place_2->setAutoDefault(false);
        choosePlacesButton = new QPushButton(PlacesWindow);
        choosePlacesButton->setObjectName(QString::fromUtf8("choosePlacesButton"));
        choosePlacesButton->setGeometry(QRect(110, 250, 161, 61));
        QFont font;
        font.setPointSize(18);
        choosePlacesButton->setFont(font);
        choosePlacesButton->setCursor(QCursor(Qt::PointingHandCursor));
        choosePlacesButton->setMouseTracking(false);
        choosePlacesButton->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.505208, y1:0.0797727, x2:0.510417, y2:1, stop:0 rgba(0, 0, 0, 204), stop:1 rgba(59, 59, 59, 255));"));
        choosePlacesButton->setAutoDefault(false);
        backButton = new QPushButton(PlacesWindow);
        backButton->setObjectName(QString::fromUtf8("backButton"));
        backButton->setGeometry(QRect(10, 10, 50, 50));
        backButton->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0.505208, y1:0.0797727, x2:0.510417, y2:1, stop:0 rgba(0, 0, 0, 204), stop:1 rgba(59, 59, 59, 255));\n"
"font: 24pt \".AppleSystemUIFont\";"));
        backButton->setIconSize(QSize(16, 16));
        backButton->setAutoDefault(false);

        retranslateUi(PlacesWindow);

        QMetaObject::connectSlotsByName(PlacesWindow);
    } // setupUi

    void retranslateUi(QDialog *PlacesWindow)
    {
        PlacesWindow->setWindowTitle(QApplication::translate("PlacesWindow", "Dialog", nullptr));
        place_72->setText(QString());
        place_80->setText(QString());
        place_56->setText(QString());
        place_85->setText(QString());
        place_61->setText(QString());
        place_101->setText(QString());
        place_69->setText(QString());
        place_109->setText(QString());
        place_14->setText(QString());
        place_22->setText(QString());
        place_114->setText(QString());
        place_27->setText(QString());
        place_75->setText(QString());
        place_83->setText(QString());
        place_45->setText(QString());
        place_17->setText(QString());
        place_50->setText(QString());
        place_25->setText(QString());
        place_58->setText(QString());
        place_119->setText(QString());
        place_46->setText(QString());
        place_65->setText(QString());
        place_95->setText(QString());
        place_33->setText(QString());
        place_79->setText(QString());
        place_87->setText(QString());
        place_63->setText(QString());
        place_103->setText(QString());
        place_92->setText(QString());
        place_68->setText(QString());
        place_108->setText(QString());
        place_116->setText(QString());
        place_31->setText(QString());
        place_21->setText(QString());
        place_121->setText(QString());
        place_77->setText(QString());
        place_98->setText(QString());
        place_104->setText(QString());
        place_82->setText(QString());
        place_90->setText(QString());
        place_106->setText(QString());
        place_19->setText(QString());
        place_38->setText(QString());
        place_52->setText(QString());
        place_24->setText(QString());
        place_48->setText(QString());
        place_36->setText(QString());
        place_53->setText(QString());
        place_12->setText(QString());
        place_4->setText(QString());
        place_81->setText(QString());
        place_7->setText(QString());
        place_86->setText(QString());
        place_94->setText(QString());
        place_70->setText(QString());
        place_110->setText(QString());
        place_8->setText(QString());
        place_115->setText(QString());
        place_30->setText(QString());
        place_40->setText(QString());
        place_84->setText(QString());
        place_9->setText(QString());
        place_111->setText(QString());
        place_57->setText(QString());
        place_113->setText(QString());
        place_26->setText(QString());
        place_59->setText(QString());
        place_71->setText(QString());
        place_47->setText(QString());
        place_55->setText(QString());
        place_29->setText(QString());
        place_37->setText(QString());
        place_60->setText(QString());
        place_100->setText(QString());
        place_34->setText(QString());
        place_13->setText(QString());
        place_96->setText(QString());
        place_15->setText(QString());
        place_88->setText(QString());
        place_74->setText(QString());
        place_35->setText(QString());
        place_93->setText(QString());
        place_97->setText(QString());
        place_117->setText(QString());
        place_32->setText(QString());
        place_44->setText(QString());
        place_122->setText(QString());
        place_16->setText(QString());
        place_89->setText(QString());
        place_99->setText(QString());
        place_6->setText(QString());
        place_91->setText(QString());
        place_118->setText(QString());
        place_64->setText(QString());
        place_1->setText(QString());
        place_66->setText(QString());
        place_28->setText(QString());
        place_73->setText(QString());
        place_49->setText(QString());
        place_78->setText(QString());
        place_39->setText(QString());
        place_54->setText(QString());
        place_3->setText(QString());
        place_62->setText(QString());
        place_102->setText(QString());
        place_67->setText(QString());
        place_107->setText(QString());
        place_20->setText(QString());
        place_76->setText(QString());
        place_42->setText(QString());
        place_105->setText(QString());
        place_41->setText(QString());
        place_43->setText(QString());
        place_18->setText(QString());
        place_51->setText(QString());
        place_23->setText(QString());
        place_112->setText(QString());
        place_11->setText(QString());
        place_120->setText(QString());
        place_5->setText(QString());
        place_10->setText(QString());
        place_2->setText(QString());
        choosePlacesButton->setText(QApplication::translate("PlacesWindow", "Buy tickets", nullptr));
        backButton->setText(QApplication::translate("PlacesWindow", "<-", nullptr));
    } // retranslateUi

};

namespace Ui {
    class PlacesWindow: public Ui_PlacesWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PLACESWINDOW_H
